// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpNxbEDdg2xO1LBtB8ktTKOI4BogDfBFg',
    appId: '1:910834792884:web:59018e5ed606e4434b1ae1',
    messagingSenderId: '910834792884',
    projectId: 'notifications-71aa3',
    authDomain: 'notifications-71aa3.firebaseapp.com',
    storageBucket: 'notifications-71aa3.firebasestorage.app',
    measurementId: 'G-CVMDQV0HJ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvoq5JiJDWQglIbhnoFKfKVTqSRkFiQVk',
    appId: '1:910834792884:android:8c9e0ee9c8cbbedc4b1ae1',
    messagingSenderId: '910834792884',
    projectId: 'notifications-71aa3',
    storageBucket: 'notifications-71aa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVVnASbWXnSIvOh1ca3jEQYBdPisRUIRc',
    appId: '1:910834792884:ios:a2943459e05d784c4b1ae1',
    messagingSenderId: '910834792884',
    projectId: 'notifications-71aa3',
    storageBucket: 'notifications-71aa3.firebasestorage.app',
    iosBundleId: 'com.example.v1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVVnASbWXnSIvOh1ca3jEQYBdPisRUIRc',
    appId: '1:910834792884:ios:a2943459e05d784c4b1ae1',
    messagingSenderId: '910834792884',
    projectId: 'notifications-71aa3',
    storageBucket: 'notifications-71aa3.firebasestorage.app',
    iosBundleId: 'com.example.v1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpNxbEDdg2xO1LBtB8ktTKOI4BogDfBFg',
    appId: '1:910834792884:web:1f845ca3e70b92fa4b1ae1',
    messagingSenderId: '910834792884',
    projectId: 'notifications-71aa3',
    authDomain: 'notifications-71aa3.firebaseapp.com',
    storageBucket: 'notifications-71aa3.firebasestorage.app',
    measurementId: 'G-VQFNL6RW50',
  );
}
